### PR TITLE
Update local development instructions to run fully containerized for dev consistency

### PR DESCRIPTION
**Pull request by dinoboy197**
Each developer's workstation is set up differently. Because of this, there can be variability in how the local environment may run (or not run) HIERR due to different shared libraries or other dependencies being installed (or not installed).

This PR fully containerizes the HIERR app when run locally, ensuring complete consistency when developing.

### CODE REVIEW

**Review by avenmia — APPROVED** [review]
lgtm!

**Comment by dinoboy197** [comment]
@avenmia I can't merge this as the repo branch protection rules are configured to require a build with Node 16.x, and [your PR here removed the Node 16.x build](https://github.com/CodeWithAloha/HIERR/pull/212/files#diff-a583f7935a5f3192471a2999cbf059eadc857228b5be2c7247f481b799949f8dL16).

If you give me repo admin, I can remove the requirement to have a Node 16.x build pass (and replace it with a Node 20.x) build. Once that I happens, I'll trigger a rebuild of this branch and I can merge.

**Comment by avenmia** [comment]
> @avenmia I can't merge this as the repo branch protection rules are configured to require a build with Node 16.x, and [your PR here removed the Node 16.x build](https://github.com/CodeWithAloha/HIERR/pull/212/files#diff-a583f7935a5f3192471a2999cbf059eadc857228b5be2c7247f481b799949f8dL16).
> 
> If you give me repo admin, I can remove the requirement to have a Node 16.x build pass (and replace it with a Node 20.x) build. Once that I happens, I'll trigger a rebuild of this branch and I can merge.

@dinoboy197  Should be fixed 👍

**Comment by dinoboy197** [comment]
> @dinoboy197 Should be fixed 👍

Awesome, thanks!

**Pull request merged**
